---

- include: link_files.yml
  with_items:
    - "{{ symlink_file_globs }}"
  loop_control:
    loop_var: link

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - "{{ copy_files }}"

- name: Symlink files
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - "{{ link_files }}"
